# Generated by Django 5.0.4 on 2024-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_good_news_profile_email_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
