# Generated by Django 5.0.4 on 2024-05-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_categories_alter_add_a_recipe_model_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_a_recipe_model',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
