# Generated by Django 5.0.6 on 2024-06-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_home_model_my_file_remove_home_model_my_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_model',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='home_model',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
