# Generated by Django 5.0.6 on 2024-06-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_rename_description_home_model_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='imge',
        ),
        migrations.AddField(
            model_name='detail',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='text',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
