# Generated by Django 5.0.6 on 2024-06-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_remove_detail_imge_detail_photo_detail_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
