# Generated by Django 5.0.6 on 2024-06-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_adddetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddetail',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
