# Generated by Django 5.0.6 on 2024-06-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_adddetail_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddetail',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
