# Generated by Django 5.0.6 on 2024-06-22 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_adddetailmodel_delete_detail'),
        ('recipes', '0017_adddetail_slug_detail_slug'),
    ]

    operations = [
    ]
