# Generated by Django 5.0.6 on 2024-06-25 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_detail_delete_adddetailmodel_adddetail_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddDetail',
        ),
    ]
